// template/FullStack/React(Frontend)+Nodejs(Backend)/client/src/pages/Signin.jsx
import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';

const Signin = () => {
  const [formData, setFormData] = useState({
  });

  const [errors, setErrors] = useState({});
  const [serverError, setServerError] = useState('');
  const [successMessage, setSuccessMessage] = useState('');
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.id]: e.target.value });
  };

  const validate = () => {
    const errors = {};


    if (!formData.emailid.trim()) {
      errors.emailid = 'Email is required';
    } else if (
      !/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i.test(formData.emailid)
    ) {
      errors.emailid = 'Email address is invalid';
    }

    if (!formData.password) {
      errors.password = 'Password is required';
    } else if (formData.password.length < 6) {
      errors.password = 'Password needs to be at least 6 characters';
    }

    return errors;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    const validationErrors = validate();
    if (Object.keys(validationErrors).length > 0) {
      setErrors(validationErrors);
      return;
    }

    try {
      const res = await fetch('http://localhost:3000/api/auth/signin', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData),
      });
    
      // Check if the response is not successful
      setLoading(false);
      if (!res.ok) {
        throw new Error('Failed to sign in');
      } else if (res.ok) {
        navigate('/');
      }
    
      const data = await res.json();
      if (!data.success === false) {
        return setErrorMessage(data.message);
      }
      setSuccessMessage('Signin successful!');
      setServerError('');
    } catch (error) {
      setServerError(error.message || 'An error occurred during signup');
      setSuccessMessage('');
    }
  };

  return (
    <div className="flex items-center justify-center min-h-screen">
      <div className="w-full max-w-md p-8 space-y-6 bg-white border-4 border-black-800 rounded-lg shadow-xl">
        <h2 className="text-3xl font-bold text-center">Log In</h2>
        <form className="space-y-5" onSubmit={handleSubmit}>

          {/* Email */}
          <div>
            <label
              htmlFor="emailid"
              className="block mb-2 text-sm font-medium"
            >
              Email Address
            </label>
            <input
              type="email"
              name="emailid"
              id="emailid"
              value={formData.emailid}
              onChange={handleChange}
              className={`w-full px-4 py-2 text-sm border-2 rounded-md focus:outline-none focus:ring-2 ${
                errors.emailid ? 'border-red-500' : ''
              }`}
              placeholder="Enter your email"
            />
            {errors.emailid && (
              <p className="mt-2 text-sm text-red-500">{errors.emailid}</p>
            )}
          </div>

          {/* Password */}
          <div>
            <label
              htmlFor="password"
              className="block mb-2 text-sm font-medium"
            >
              Password
            </label>
            <input
              type="password"
              name="password"
              id="password"
              value={formData.password}
              onChange={handleChange}
              className={`w-full px-4 py-2 text-sm border-2 rounded-md focus:outline-none focus:ring-2 ${
                errors.password ? 'border-red-500' : ''
              }`}
              placeholder="Enter your password"
            />
            {errors.password && (
              <p className="mt-2 text-sm text-red-500">{errors.password}</p>
            )}
          </div>

          {/* Server Error */}
          {serverError && (
            <p className="mt-2 text-sm text-red-500">{serverError}</p>
          )}

          {/* Success Message */}
          {successMessage && (
            <p className="mt-2 text-sm text-green-500">{successMessage}</p>
          )}

          {/* Submit Button */}
          <button
            type="submit"
            className="w-full px-4 py-2 text-sm font-medium text-white bg-gradient-to-r from-green-400 to-blue-500 rounded-md hover:bg-blue-600 focus:outline-none focus:ring-2"
          >
            Sign In
          </button>
        </form>

        {/* Additional Links */}
        <p className="text-sm text-center text-gray-600">
          Don't have an account?{' '}
          <a href="/signup" className="text-blue-500 hover:underline">
            Sign Up
          </a>
        </p>
      </div>
    </div>
  );
};

export default Signin;

// template/FullStack/Vue(Frontend)+Express(Backend)/client/src/views/Signin.vue
<template>
  <div class="flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
    <div class="w-full max-w-md space-y-8">
      <div class="bg-white p-8 border-4 border-black-800 rounded-lg shadow-xl">
        <h2 class="text-3xl font-bold text-center mb-6">Sign In</h2>
        <form class="space-y-6" @submit.prevent="handleSubmit">
          <div>
            <label for="emailid" class="block mb-2 text-sm font-medium">Email Address</label>
            <input
              type="email"
              id="emailid"
              v-model="formData.emailid"
              :class="{'border-red-500': errors.emailid}"
              class="w-full px-4 py-2 text-sm border-2 rounded-md focus:outline-none focus:ring-2"
              placeholder="Enter your email"
            />
            <p v-if="errors.emailid" class="mt-2 text-sm text-red-500">{{ errors.emailid }}</p>
          </div>
          <div>
            <label for="password" class="block mb-2 text-sm font-medium">Password</label>
            <input
              type="password"
              id="password"
              v-model="formData.password"
              :class="{'border-red-500': errors.password}"
              class="w-full px-4 py-2 text-sm border-2 rounded-md focus:outline-none focus:ring-2"
              placeholder="Enter your password"
            />
            <p v-if="errors.password" class="mt-2 text-sm text-red-500">{{ errors.password }}</p>
          </div>
          <p v-if="serverError" class="mt-2 text-sm text-red-500">{{ serverError }}</p>
          <p v-if="successMessage" class="mt-2 text-sm text-green-500">{{ successMessage }}</p>
          <button
            type="submit"
            :disabled="loading"
            class="w-full px-4 py-2 text-sm font-medium text-white bg-gradient-to-r from-green-400 to-blue-500 rounded-md hover:bg-blue-600 focus:outline-none focus:ring-2 disabled:opacity-50"
          >
            {{ loading ? 'Signing In...' : 'Sign In' }}
          </button>
        </form>
        <p class="mt-4 text-sm text-center text-gray-600">
          Don't have an account?
          <router-link to="/signup" class="text-blue-500 hover:underline">
            Sign Up
          </router-link>
        </p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { useForm, commonValidations } from '../composables/useForm'
import { useAuthStore } from '../stores/auth'
import { useRouter } from 'vue-router'

const authStore = useAuthStore()
const router = useRouter()

const initialState = {
  emailid: '',
  password: '',
}

const validations = {
  emailid: (value) => commonValidations.required('Email')(value) || commonValidations.email(value),
  password: commonValidations.required('Password'),
}

const submitAction = async (formData) => {
  await authStore.signin(formData)
  return 'Signin successful!'
}

const {
  formData,
  errors,
  serverError,
  successMessage,
  loading,
  handleSubmit,
} = useForm(initialState, validations, submitAction)

handleSubmit.onSuccess = () => {
  router.push('/account')
}
</script>
