// template/FullStack/Vite(Frontend)+Flask(Backend)/client/src/pages/Signin.tsx
"use client";
import React, { useState } from "react";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";

import { Link, useNavigate } from 'react-router-dom';
import { toast } from "sonner"

const BACKEND_URL = import.meta.env.VITE_BACKEND_URL || "http://localhost:5000";

export default function Signin() {
    const [formData, setFormData] = useState({ username: "", password: "" });
    const navigate = useNavigate();

    const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();

        try {
            const response = await fetch(`${BACKEND_URL}/signin`, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify(formData),
            });

            if (response.ok) {
                const data = await response.json();
                toast.success("Signin Successfull",{
                    description: `Welcome, ${data.user.username}`
                });
                navigate("/home");
            } else {
                const errorData = await response.json();
                toast.error("Signin failed",{
                    description: errorData.message || "Signin failed.",
                });
            }
        } catch (error) {
            toast.error("Signin failed",{
                description: `Something went wrong. Please try again. ${error}`
            });
        }
    };

    return (
        <div className="min-h-screen flex items-center justify-center">
            <div className="max-w-md w-full mx-auto rounded-none md:rounded-2xl p-4 md:p-8 shadow-input bg-white dark:bg-black">
                <h2 className="font-bold text-xl text-neutral-800 dark:text-neutral-200 text-center mb-4">
                    Signin
                </h2>
                <form className="my-8" onSubmit={handleSubmit}>
                    <LabelInputContainer className="mb-4">
                        <Label htmlFor="username">Username</Label>
                        <Input
                            id="username"
                            placeholder="Your username"
                            type="text"
                            value={formData.username}
                            onChange={(e) => setFormData({ ...formData, username: e.target.value })}
                        />
                    </LabelInputContainer>
                    <LabelInputContainer className="mb-4">
                        <Label htmlFor="password">Password</Label>
                        <Input
                            id="password"
                            placeholder="••••••••"
                            type="password"
                            value={formData.password}
                            onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                        />
                    </LabelInputContainer>

                    <button
                        className="bg-gradient-to-br relative group/btn from-black dark:from-zinc-900 dark:to-zinc-900 to-neutral-600 block dark:bg-zinc-800 w-full text-white rounded-md h-10 font-medium shadow-[0px_1px_0px_0px_#ffffff40_inset,0px_-1px_0px_0px_#ffffff40_inset] dark:shadow-[0px_1px_0px_0px_var(--zinc-800)_inset,0px_-1px_0px_0px_var(--zinc-800)_inset]"
                        type="submit"
                    >
                        Sign in &rarr;
                        <BottomGradient />
                    </button>

                    <p className="text-center text-sm text-gray-600 dark:text-gray-400 mt-4">
                        Don’t have an account?{' '}
                        <Link to="/signup" className="text-blue-600 hover:underline dark:text-blue-400">
                            Sign up
                        </Link>
                    </p>

                    
                </form>
            </div>
        </div>
    );
}

const BottomGradient = () => {
    return (
        <>
            <span className="group-hover/btn:opacity-100 block transition duration-500 opacity-0 absolute h-px w-full -bottom-px inset-x-0 bg-gradient-to-r from-transparent via-cyan-500 to-transparent" />
            <span className="group-hover/btn:opacity-100 blur-sm block transition duration-500 opacity-0 absolute h-px w-1/2 mx-auto -bottom-px inset-x-10 bg-gradient-to-r from-transparent via-indigo-500 to-transparent" />
        </>
    );
};

const LabelInputContainer = ({
    children,
    className,
}: {
    children: React.ReactNode;
    className?: string;
}) => {
    return (
        <div className={cn("flex flex-col space-y-2 w-full", className)}>
            {children}
        </div>
    );
};

// template/FullStack/Vue(Frontend)+GoFiber(Backend)/client/src/views/Signin.vue


<template>
  <div class="flex items-center justify-center py-8 bg-gray-900">
    <div class="w-full max-w-md p-8 space-y-8 bg-gray-800 border border-gray-700 rounded-lg shadow-xl">
      <h2 class="text-3xl font-bold text-center text-white">Sign In</h2>
      <form @submit.prevent="handleSubmit" class="space-y-6">
        <BaseInput
          id="emailid"
          label="Email Address"
          v-model="formData.emailid"
          :error="errors.emailid"
          type="email"
          placeholder="Enter your email"
        />
        <BaseInput
          id="password"
          label="Password"
          v-model="formData.password"
          :error="errors.password"
          type="password"
          placeholder="Enter your password"
        />
        <button
          type="submit"
          :disabled="loading"
          class="w-full px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-50"
        >
          {{ loading ? 'Signing In...' : 'Sign In' }}
        </button>
      </form>
      <p class="mt-4 text-sm text-center text-gray-400">
        Don't have an account?
        <router-link to="/signup" class="text-blue-400 hover:underline">
          Sign Up
        </router-link>
      </p>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useAuthStore } from '../stores/auth'
import { useRouter } from 'vue-router'
import { useToast } from 'vue-toastification'
import { commonValidations } from '../composables/useForm'
import BaseInput from '../components/BaseInput.vue'

const authStore = useAuthStore()
const router = useRouter()
const toast = useToast()

const formData = ref({
  emailid: '',
  password: '',
})

const errors = ref({})
const loading = ref(false)

const validateForm = () => {
  errors.value = {
    emailid: commonValidations.required('Email')(formData.value.emailid) || commonValidations.email(formData.value.emailid),
    password: commonValidations.required('Password')(formData.value.password),
  }
  return Object.values(errors.value).every(error => !error)
}

const handleSubmit = async () => {
  if (!validateForm()) return

  loading.value = true
  try {
    await authStore.signin(formData.value)
    await router.push('/snippets')
    toast.success('Signed in successfully!')
  } catch (error) {
    toast.error(`Error: ${error.response?.data?.message || error.message}`)
  } finally {
    loading.value = false
  }
}
</script>
